openapi: 3.0.0
info:
  title: My Users API
  description: This is a simple API to demonstrate Swagger documentation
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /users:
    get:
      summary: Retrieve a list of users
      description: Retrieve a list of users in the system
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Create a new user
      requestBody:
        description: User object that needs to be added to the system
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
      responses:
        "201":
          description: User created successfully
